name: CD Pipeline
on:
    workflow_run:
        workflows: ["CI pipeline"]
        types:
            - completed
jobs:
    build:
        runs-on: self-hosted
        steps:
           
            - name: Delete Old Docker Container
              run:  sudo docker rm -f backend || true

            - name: Delete Image
              run: sudo docker image rmi ndambuki/google-io || true

            - name: Pull Docker Image
              run: sudo docker pull ndambuki/google-io

            - name: Run Docker Container
              run: sudo docker run  -d -p 80:80 --name backend ndambuki/google-io
